services:
  nudges:
    build: .
    command: uvicorn main:app --reload --port=8000 --host=0.0.0.0
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - .postgres/book_service.sql:/docker-entrypoint-initdb.d/book_service.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    expose:
      - 5432:5432
    ports:
      - 5432:5432

volumes:
  postgres_data: